README.md

The existing instructions that indicate one should install the C# Dev Kit is potentially a violation of ToS / Licensing, the C# Dev Kit is licensed to only be used with Visual Studio Code.
However the specific nuget package we need (Microsoft.CodeAnalysis.LanguageServer) is explicitly broken out to be licensed for open use, so we want to instruct people to download it directly to avoid encouraging people to potentially violate license agreements (and potential irk microsoft's legal team)
Downloading it directly off their nuget feed and then unpacking it is the best way to stick to their license on the package (and it means not needing to have to install VS Code and a plugin for it at all)

Update README.md with more detailed install instructions

---

lua/roslyn/init.lua
lua/roslyn/slnutils.lua

Selecting the proper SLN every time we open some multi-SLN solution is a bit inconvenient. This change is trying to automate the selection of proper SLN file. The selection algorithm is rather simple. It just checks all the SLN files for the definition of the csproj file that we're currently "in" (using the closest csproj in the parent dirs).
It also renames/reorganizes some stuff, hopefuly for the better.

Predict correct SLN file

---

lua/roslyn/hacks.lua
lua/roslyn/init.lua

Extends the language server finding logic to support an executable available in `PATH`
This is to cater to my personal use case, where I have the lsp installed via a method other than mason (nix)
Closes #14

Allow using already wrapped executable

---

lua/roslyn/init.lua
lua/roslyn/server.lua
lua/roslyn/slnutils.lua

This makes a couple of changes:
- We only store a single known solution file. The reason for this, is that it seems to really not work with multiple solutions, and this is a bit more close to how vscode handles it (It seems like)
- Stop the server between changing targets with `CSTarget`
- Custom method for reusing the server if we have a solution (I have a project where I have multiple csproj-files that is not necessarily a child of where the solution file is. The current implementation makes this not work
-  Use BufEnter for the autocmd instead of `FileType`. If changing back and forth, it will not create a `CSTarget` user command with the `FileType` event. This is because this is only fired once per buffer.
In some cases, this also removes the notify of multiple solution files found. I …

Support only a single known solution at a time

---

README.md
lua/roslyn/commands.lua
lua/roslyn/init.lua

Allow for user custom on_init, on_exit hooks & fix encoding used for code actions
Supersedes https://github.com/seblj/roslyn.nvim/pull/35

Allow for user custom on_init, on_exit hooks

---

lua/roslyn/init.lua
lua/roslyn/slnutils.lua

Mostly, this is a bit of a change in how it decides to attach to either a project or a solution.
- It will attach to csproj if neovim is opened where a solution file does not exist in cwd or in any subdirectories.
- It wil however only do this if the file opened from neovim is actually in any subdirectories.
- If not, then it will fallback to the previous way of deciding

Prefer attach to project (in some cases)

---

lua/roslyn/init.lua
lua/roslyn/server.lua

This should properly spawn new servers if a different project is opened in the same neovim session.
Previously, it would just use the already selected sln.
This should change that so that if I am attached to the solution
`~/foo/foo.sln`, and I suddenly open a file in a totally different project
`~/bar/bar.sln`.
This will now start a new server instead of trying to reuse the same one.
Reusing the same one didn't seem to work properly.
This should only be for edge cases where someone might jump back and forth between projects like this, but I am still not 100% sure that I want this. I will be using this for a little while and see if I have some issues with it. Feel free to comment if you stumble across this, and let me know your opinion!

fix: properly spawn new language server if needed

---

lua/roslyn/slnutils.lua

fixes: #45
This changes the behaviour since we would stop looking for .csproj and .sln files for all the directories inside the root directory. I don't know if this is so important but, if it is, we could provide two ways of search (broad and narrow) in some kind of option (I think that narrow would be the better default).
If there are anything that needs change, please let me know.

perf: changing the way to search for .csproj and .sln files to reduce the number of analyzed files

---

lua/roslyn/init.lua
lua/roslyn/slnutils.lua

I now realise I don't think it was broad search for solution file that was slow, and it was really just trying to get csproj file in a really bad way. The current way of trying to attach to only a single project seems to be just what I need at least. (I don't even remember why I made it so complicated in the beginning)
I am kind of tempted to not have this optional and just have this as the only default, but it was so little code for an option, so I will probably keep this opt-in until someone potentially argues that this should be the default.

feat: add option for broad sln search

---

README.md
lua/roslyn/commands.lua
lua/roslyn/init.lua

Problem:
* Autocmd: Using the BufRead autocmd means that the buffer must be focused in order to attach the LSP. As part of the integration with rzls for Razor support a virtual buffer is opened headlessly. This means that the LSP does not attach until the user BufEnters
* Lsp Cmd: Currenly it was not possible to add extra flags to the LSP start when using a mason installation.
Solution:
* Autocmd: Change to FileType Autocmd
* Lsp Cmd: Add wrapper to allow extension of Mason supplied path with either a table of a string of arguments

refator: FileType Autocmd and path configuration

---

lua/roslyn/init.lua
lua/roslyn/server.lua

Lets us not expose `save_server_object` and also have all of this annoying logic in one place

fix: move pipe callback into server

---

lua/roslyn/sln/utils.lua

The condition `not sln or not csproj` in sln.utils.root_dir was causing roslyn not to attach to cs buffer if one of .csproj or .sln was not found via `vim.fs.root_dir`
This behavior was introduced relatively recently in d121ca7d067c9b25a09990ccebb8eaa11710efbf
The fix updates the condition to allow for only one of these being found (the rest of the code already seems to account for it). After updating the condition, find_files_with_extension(sln, ".sln") was breaking as well, so I wrapped those calls in their own separate conditions based on if .csproj or .sln root directories were found.
Existing github issue: #87

fix: roslyn doesn't attach to cs buffer when .sln is not present

---

lua/roslyn/server.lua

- Added a delay to `start_pending` reset to give the server some time to initialize properly.
- Adjusted the delay for retrying server start to handle multiple instances of roslyn servers.
I am trying some speed ups to rzls, which means I need to slow roslyn down (but only if you are trying to spawn lots of roslyn processes at once)

fix(server): adjust server spawn resets

---

lua/roslyn/sln/api.lua
lua/roslyn/sln/utils.lua

Currently at my work we have multiple csprojs, the actual csproj and then a backup like so
Backup.Project.csproj
Project.csproj
The Backup csproj is not referenced in the sln, not sure why this is the case but it is.
In this scenario predict_sln_file will just return nil and the lsp will spawn on the csproj only.
Not sure if my solution is the best, happy to try implement any better suggested solutions. I'm also a bit of a newbie when it comes to lua, neovim and contributing to open source, so any feedback is welcome

Fix multiple csprojs 

---

lua/roslyn/init.lua
lua/roslyn/lsp.lua

This PR adds support for opening and handling source generated documents. The reloading of open source generated documents is currently not implement, but should not be to hard to add.
The "BufReadCmd" callback is inspired by https://github.com/mfussenegger/nvim-jdtls/blob/master/lua/jdtls.lua#L1186 (including the vim.wait call).
The VsCode extension has also added support for source generated documents. (initial: https://github.com/dotnet/vscode-csharp/pull/7581, refresh support: https://github.com/dotnet/vscode-csharp/pull/7791, src location: `https://github.com/dotnet/vscode-csharp/blob/main/src/lsptoolshost/sourceGeneratedFilesContentProvider.ts)
Notes from manual testing:
The VsCode extension and this extension returns some times different results when executing the "go to reference" …

Add support for opening source generated documents

---

lua/roslyn/sln/utils.lua

We could just broad seach from `pwd`, but I don't know if I want it because the user might open the file from home, and then it would search _a lot_ of files. Git root is probably good enough?

fix: broad search from git root for sln

---

lua/roslyn/sln/utils.lua

Re perf comment
> I think we should try and combine some of the vim.fs.root and vim.fs.find methods in the utils.root method. I have gotten a couple of issues earlier about performance when finding the solution file, and this adds even more filesystem searching.
Speeds up my (very) large solution search by ~10x from ~2180ms to ~ 201ms.
I tried combining the `vim.fs.root` methods, and it works, but the perf gains are minimal so I will do as part of solution filter support if it becomes more measurable.
`find_solutions` is essentially a stripped down copy of `vim.fs.find`, the important bit being it skips based on `ignore_dir`. Currently, this just skips dotnet's `bin` and `obj` folders, but could be expanded for things like `.vs/`, `.vscode/`, `.idea/`, etc.

Ignore bin and obj folders in broad solution search

---

lua/roslyn/commands.lua
lua/roslyn/config.lua
lua/roslyn/init.lua
lua/roslyn/sln/api.lua
lua/roslyn/sln/utils.lua

Closes #125
The options in the select targets list now look much the same as "Open Solution" in VSCode. Could be cool to do a proximity sort or something in the future...
I've left out flowing solution filters through to `predict_sln_file` to avoid behaviour changes, which means they can only be selected manually for now. In a future release it'd be handy to flow them through to `choose_target`, if and when you decide to rename the options, as discussed in the issue. I'll probably do so in my fork in the meantime, so feel free to ping me for a PR if wanted.

Support targeting solution filters

---

lua/roslyn/commands.lua
lua/roslyn/sln/api.lua
lua/roslyn/sln/utils.lua

Adds support for the new slnx file format. Treats slnx and sln as interchangeable. I think this makes sense as the purpose of the file is the same, and the contents should also represent the same
Implemented the same for easy-dotnet.nvim
- gustaveikaas/easy-dotnet.nvim#220
Also fixed a bug with the `Roslyn target` command. `require("roslyn.utils")` -> `require("roslyn.sln.utils")`

feat: add slnx support

---

lua/roslyn/config.lua
lua/roslyn/lsp.lua

- Added a check for the `--stdio` argument in `config.lua` to ensure it is
present in the configuration. If not, it will be added and a warning
notification will be shown.
- Moved the `RoslynInitialized` autocmd execution in `lsp.lua` to ensure it
runs before refreshing diagnostics.
- Added global variable for checking if roslyn is initialized

fix!: remove hacky pipe start and prefer stdio

---

lua/roslyn/lsp.lua

This PR adds support for refreshing open source-generated files.
The implementation is based on https://github.com/dotnet/vscode-csharp/blob/main/src/lsptoolshost/sourceGeneratedFilesContentProvider.ts.
Some implementation notes:
Sadly the updated files are not provided in the "refreshSourceGeneratedDocument" notification, so we have to iterate over all open sg files and request for each sg file the content. We provide the previous resultId of the sg file in the "sourceGeneratedDocument/_roslyn_getText" request to avoid the retrieval of unchanged sg files. Roslyn will return the same resultId and an empty document in such a case and we skip the sg file update logic.
We could also cache the open sg files in a global list to avoid iterating through all open documents (similar how the vs …

Add refresh support for source generated files

---

lua/roslyn/config.lua

Use `blink.cmp` lsp capabilities if blink is available

Add blink lsp capabilities

---

lua/roslyn/init.lua

Microsoft likes to localize absolutely anything, from excel macro names, to exception messages. Why? No clue.

Fix "missing `--stdio` argument" error not getting detected due to localization

---

README.md
lua/roslyn/config.lua
lua/roslyn/lsp.lua

In some cases, language server does not see new .cs files. This breaks autocomplete, diagnostics and navigation. Restarting the server helps to solve the problem, but it's inconvenient to do it every time.
As discussed here https://github.com/seblyng/roslyn.nvim/issues/15 there is no good solution to fix the issue. There are only various hacks that can make life easier. So, I suggest changing `filewatching` option and adding another hack that disables `workspace.didChangeWatchedFiles.dynamicRegistration` in client capabilities.
Before
```lua
---@field filewatching boolean
```
After
```lua
---@field filewatching string auto | force-nvim | force-ls
```
Where:
* `auto` - do nothing and keep everything as is (default value) [same as old filewatching = true];
* `force-nvim` - indicates to the …

Extending filewatching option

---

README.md

Hi!
What do you think about adding type annotations for the config in the readme? This would make it easier to configure the plugin with just lsp, without going to the browser.
With type annotations:
And without:
There is one problem: when describing `vim.lsp.ClientConfig` (config node), we will get missing-fields diagnostics if cmd is not defined. I solved this by ignoring this diagnostic `---@diagnostic disable-next-line: missing-fields`, because the plugin starts the server correctly without cmd definition.
```lua
---@module 'roslyn.config'
---@type RoslynNvimConfig
opts = {
filewatching = 'roslyn',
---@diagnostic disable-next-line: missing-fields
config = {
settings = {
<my settings>
},
},
}
```

docs: Add type annotations to the plugin installation snippet

---

lua/roslyn/config.lua
lua/roslyn/init.lua
lua/roslyn/sln/api.lua

This code has been deprecated for some time now, and needs to be removed I want to do this before refactoring a bit with some (unfortunately) breaking changes for nvim 0.11 and vim.lsp.config
However, I will wait some time before merging something like that and bump minimum required version to 0.11

fix!: remove some code that has been deprecated for a while

---

README.md
lua/roslyn/config.lua
lua/roslyn/lsp.lua

While working on #178 I think I have finally gotten `vim.lsp.enable` to work. However, with that, I can't seem to find a good way to resolve this legacy config and warn the users about deprecated options.
Because of this, I think I want to soft deprecate these now. Warn the users if they are using them, but still resolve them.
Also warn about the default install location of roslyn. User now needs to provide this themselves

fix!: deprecate exe and args options and default cmd location

---

lsp/roslyn.lua

This change ensures that when opening source-generated files (e.g., via Go to Definition), the existing Roslyn LSP client is reused if available, instead of launching a new server instance.
This avoids the issue where a second server attaches to the buffer and clears its contents.
Fixes the issue described here: https://github.com/seblyng/roslyn.nvim/issues/226

Fix: prevent duplicate Roslyn servers for source-generated files

---

README.md
lsp/roslyn.lua

fix: default to same cmd as nvim-lspconfig if roslyn is not found
